DROP TABLE IF EXISTS variants;
DROP SEQUENCE IF EXISTS variants_id_seq;

DROP TABLE IF EXISTS atributes;
DROP SEQUENCE IF EXISTS atributes_id_seq;

CREATE SEQUENCE atributes_id_seq
  AS INTEGER
  START WITH 1;
CREATE TABLE atributes (
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE atributes_id_seq PRIMARY KEY,
  name        LONGVARCHAR NOT NULL,
  description LONGVARCHAR
);

CREATE SEQUENCE variants_id_seq
  AS INTEGER
  START WITH 1;
CREATE TABLE variants (
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE variants_id_seq PRIMARY KEY,
  name        LONGVARCHAR NOT NULL,
  description LONGVARCHAR,
  atribute_id INTEGER,
  FOREIGN KEY (atribute_id) REFERENCES atributes (id)
    ON DELETE CASCADE
);


DROP TABLE IF EXISTS users;
DROP SEQUENCE IF EXISTS users_id_seq;
CREATE SEQUENCE users_id_seq
  AS INTEGER
  START WITH 1;
CREATE TABLE users (
  id       INTEGER GENERATED BY DEFAULT AS SEQUENCE users_id_seq PRIMARY KEY,
  name     LONGVARCHAR NOT NULL,
  email    LONGVARCHAR NOT NULL,
  password LONGVARCHAR NOT NULL,
  role     INTEGER     NOT NULL
);
/*
DROP TABLE IF EXISTS products;
DROP SEQUENCE IF EXISTS products_id_seq;

DROP TABLE IF EXISTS categorys;
DROP SEQUENCE IF EXISTS categorys_id_seq;


CREATE SEQUENCE categorys_id_seq AS INTEGER START WITH 1;
CREATE TABLE categorys(
  id              INTEGER GENERATED BY DEFAULT AS SEQUENCE products_id_seq PRIMARY KEY,
  parrent_cat_id  INTEGER,
  name            LONGVARCHAR NOT NULL
);

CREATE SEQUENCE products_id_seq AS INTEGER  START WITH 1;
CREATE TABLE products(
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE products_id_seq PRIMARY KEY,
  name        LONGVARCHAR NOT NULL ,
  desciption  LONGVARCHAR NOT NULL ,
  category_id INTEGER,
  FOREIGN KEY (category_id) REFERENCES categorys (id) ON DELETE CASCADE
);
*/