-- MySQL Script generated by MySQL Workbench
-- Thu Aug 24 22:01:13 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema supSite
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema supSite
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `supSite` DEFAULT CHARACTER SET utf8 ;
USE `supSite` ;

-- -----------------------------------------------------
-- Table `supSite`.`categorys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supSite`.`categorys`;

CREATE TABLE IF NOT EXISTS `supSite`.`categorys` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parrent_cat_id` INT NULL DEFAULT  NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supSite`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supSite`.`products`;

CREATE TABLE IF NOT EXISTS `supSite`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `categorys_id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_products_categorys1_idx` (`categorys_id` ASC),
  CONSTRAINT `fk_products_categorys1`
    FOREIGN KEY (`categorys_id`)
    REFERENCES `supSite`.`categorys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supSite`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supSite`.`users`;

CREATE TABLE IF NOT EXISTS `supSite`.`users` (
  `id`       INT          NOT NULL AUTO_INCREMENT,
  `name`     VARCHAR(45)  NOT NULL,
  `email`    VARCHAR(100) NOT NULL,
  `password` VARCHAR(50)  NOT NULL,
  `role`     INT          NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supSite`.`products_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supSite`.`products_users`;

CREATE TABLE IF NOT EXISTS `supSite`.`products_users` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_users_user1_idx` (`user_id` ASC),
  INDEX `fk_products_users_products1_idx` (`products_id` ASC),
  CONSTRAINT `fk_products_users_user1`
    FOREIGN KEY (`user_id`)
  REFERENCES `supSite`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_users_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `supSite`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supSite`.`atributes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supSite`.`atributes`;

CREATE TABLE IF NOT EXISTS `supSite`.`atributes` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supSite`.`atributes_variants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supSite`.`atributes_variants`;

CREATE TABLE IF NOT EXISTS `supSite`.`atributes_variants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `atribute_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_atributes_variants_atribute1_idx` (`atribute_id` ASC),
  CONSTRAINT `fk_atributes_variants_atribute1`
    FOREIGN KEY (`atribute_id`)
    REFERENCES `supSite`.`atributes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supSite`.`categorys_atributes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supSite`.`categorys_atributes`;

CREATE TABLE IF NOT EXISTS `supSite`.`categorys_atributes` (
  `id` VARCHAR(45) NULL,
  `categorys_id` INT NOT NULL,
  `atributes_id` INT NOT NULL,
  INDEX `fk_categorys_atributes_categorys1_idx` (`categorys_id` ASC),
  INDEX `fk_categorys_atributes_atributes1_idx` (`atributes_id` ASC),
  CONSTRAINT `fk_categorys_atributes_categorys1`
    FOREIGN KEY (`categorys_id`)
    REFERENCES `supSite`.`categorys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categorys_atributes_atributes1`
    FOREIGN KEY (`atributes_id`)
    REFERENCES `supSite`.`atributes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
