-- MySQL Script generated by MySQL Workbench
-- Sat Sep  9 11:44:28 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema supSite
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `supSite` ;

-- -----------------------------------------------------
-- Schema supSite
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `supSite` DEFAULT CHARACTER SET utf8 ;
USE `supSite` ;

-- -----------------------------------------------------
-- Table `supSite`.`categorys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supSite`.`categorys` ;

CREATE TABLE IF NOT EXISTS `supSite`.`categorys` (
  `id`            INT          NOT NULL AUTO_INCREMENT,
  `parent_cat_id` INT          NULL     DEFAULT NULL,
  `name`          VARCHAR(100) NOT NULL,
  `order`         INT          NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supSite`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supSite`.`products` ;

CREATE TABLE IF NOT EXISTS `supSite`.`products` (
  `id`           INT          NOT NULL AUTO_INCREMENT,
  `name`         VARCHAR(255) NOT NULL,
  `description`  VARCHAR(45)  NULL,
  `categorys_id` INT          NOT NULL,
  `price`        REAL         NULL,
  `count`        INT          NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_products_categorys1_idx` (`categorys_id` ASC),
  CONSTRAINT `fk_products_categorys1`
  FOREIGN KEY (`categorys_id`)
  REFERENCES `supSite`.`categorys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supSite`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supSite`.`users` ;

CREATE TABLE IF NOT EXISTS `supSite`.`users` (
  `id`        INT          NOT NULL AUTO_INCREMENT,
  `name`      VARCHAR(45)  NOT NULL,
  `email`     VARCHAR(100) NOT NULL,
  `password`  VARCHAR(50)  NOT NULL,
  `role`      INT          NULL,
  `telephone` VARCHAR(45)  NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supSite`.`attributes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supSite`.`attributes` ;

CREATE TABLE IF NOT EXISTS `supSite`.`attributes` (
  `id`           INT         NOT NULL AUTO_INCREMENT,
  `name`         VARCHAR(45) NOT NULL,
  `description`  VARCHAR(45) NULL,
  `type`         VARCHAR(50) NOT NULL DEFAULT 'text',
  `categorys_id` INT         NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attributes_categorys1_idx` (`categorys_id` ASC),
  CONSTRAINT `fk_attributes_categorys1`
  FOREIGN KEY (`categorys_id`)
  REFERENCES `supSite`.`categorys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supSite`.`variants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supSite`.`variants` ;

CREATE TABLE IF NOT EXISTS `supSite`.`variants` (
  `id`           INT          NOT NULL AUTO_INCREMENT,
  `name`         VARCHAR(45)  NOT NULL,
  `description`  VARCHAR(100) NULL,
  `attribute_id` INT          NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_atributes_variants_atribute1_idx` (`attribute_id` ASC),
  CONSTRAINT `fk_atributes_variants_atribute1`
  FOREIGN KEY (`attribute_id`)
  REFERENCES `supSite`.`attributes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supSite`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supSite`.`orders` ;

CREATE TABLE IF NOT EXISTS `supSite`.`orders` (
  `id`              INT         NOT NULL AUTO_INCREMENT,
  `datetime_open`   DATETIME    NOT NULL DEFAULT now(),
  `datetime_closed` DATETIME    NULL,
  `description`     VARCHAR(45) NULL,
  `sum`             REAL        NOT NULL,
  `users_id`        INT         NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_orders_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_orders_users1`
  FOREIGN KEY (`users_id`)
  REFERENCES `supSite`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supSite`.`products_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supSite`.`products_orders` ;

CREATE TABLE IF NOT EXISTS `supSite`.`products_orders` (
  `id`          INT NOT NULL AUTO_INCREMENT,
  `orders_id`   INT NOT NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_orders_orders1_idx` (`orders_id` ASC),
  INDEX `fk_products_orders_products1_idx` (`products_id` ASC),
  CONSTRAINT `fk_products_orders_orders1`
  FOREIGN KEY (`orders_id`)
  REFERENCES `supSite`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_orders_products1`
  FOREIGN KEY (`products_id`)
  REFERENCES `supSite`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `supSite`.`products_variants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `supSite`.`products_variants`;

CREATE TABLE IF NOT EXISTS `supSite`.`products_variants` (
  `products_id` INT NOT NULL,
  `variants_id` INT NOT NULL,
  INDEX `fk_poducts_variants_products1_idx` (`products_id` ASC),
  INDEX `fk_poducts_variants_variants1_idx` (`variants_id` ASC),
  CONSTRAINT `fk_poducts_variants_products1`
  FOREIGN KEY (`products_id`)
  REFERENCES `supSite`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_poducts_variants_variants1`
  FOREIGN KEY (`variants_id`)
  REFERENCES `supSite`.`variants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
