DROP TABLE IF EXISTS variants;
DROP SEQUENCE IF EXISTS variants_id_seq;

DROP TABLE IF EXISTS attributes;
DROP SEQUENCE IF EXISTS attributes_id_seq;

CREATE SEQUENCE attributes_id_seq
  AS INTEGER
  START WITH 1;
CREATE TABLE attributes (
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE attributes_id_seq PRIMARY KEY,
  name        LONGVARCHAR NOT NULL,
  description LONGVARCHAR
);

CREATE SEQUENCE variants_id_seq
  AS INTEGER
  START WITH 1;
CREATE TABLE variants (
  id           INTEGER GENERATED BY DEFAULT AS SEQUENCE variants_id_seq PRIMARY KEY,
  name         LONGVARCHAR NOT NULL,
  description  LONGVARCHAR,
  attribute_id INTEGER,
  FOREIGN KEY (attribute_id) REFERENCES attributes (id)
    ON DELETE CASCADE
);


DROP TABLE IF EXISTS users;
DROP SEQUENCE IF EXISTS users_id_seq;
CREATE SEQUENCE users_id_seq
  AS INTEGER
  START WITH 1;
CREATE TABLE users (
  id       INTEGER GENERATED BY DEFAULT AS SEQUENCE users_id_seq PRIMARY KEY,
  name     LONGVARCHAR NOT NULL,
  email    LONGVARCHAR NOT NULL,
  password LONGVARCHAR NOT NULL,
  role     INTEGER     NOT NULL
);


DROP TABLE IF EXISTS categorys;
DROP SEQUENCE IF EXISTS categorys_id_seq;

CREATE SEQUENCE categorys_id_seq AS INTEGER START WITH 1;
CREATE TABLE categorys (
  id              INTEGER GENERATED BY DEFAULT AS SEQUENCE categorys_id_seq PRIMARY KEY,
  parent_cat_id   INTEGER DEFAULT NULL,
  name            LONGVARCHAR NOT NULL
);
/*
DROP TABLE IF EXISTS products;
DROP SEQUENCE IF EXISTS products_id_seq;

CREATE SEQUENCE products_id_seq AS INTEGER  START WITH 1;
CREATE TABLE products(
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE products_id_seq PRIMARY KEY,
  name        LONGVARCHAR NOT NULL ,
  desciption  LONGVARCHAR NOT NULL ,
  category_id INTEGER,
  FOREIGN KEY (category_id) REFERENCES categorys (id) ON DELETE CASCADE
);
*/